# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Retrieve the secret and decode it to a file
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo $NPM_TOKEN | base64 --decode > cert.der
      - name: Show certificate information
        run: |
          openssl x509 -in cert.der -inform DER -text -noout
#       - run: npm install
  # testing-app:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: node index.js
